### ISSUE TITLE
`MUD` branch discussion

### ISSUE THREAD

**Issue by MihinMUD** [TechDudie/minegame#4]
This is so I can safely test out tweaks without conflicting with the main branch. I will make pull requests to the main branch when it is ready, thanks.

**Comment by MihinMUD** [comment]
I worked on the css little bit and I improved the crafting/inventory UI quite good in my opinion. I can open a pull request to the main branch but I am not sure if it is responsive with mobile screens yet. for now this is how it looks.

![image](https://user-images.githubusercontent.com/73010893/231055383-83d5dacb-6f04-4554-bda9-93f4d9b435e5.png)

 thanks!

**Comment by MihinMUD** [comment]
Also I added a prettier config file for easier time on vscode :sweat_smile:

**Comment by MihinMUD** [comment]
@TechDudie I know you are kind of busy and sorry for that :sweat_smile: , but please check this out and tell me if I should open a pull request!

**Comment by TechDudie** [comment]
ok tysm! i'm really busy with middle school, but thanks for working on this!
